import { BaseSeeder } from '@adonisjs/lucid/seeders'
import Property from '#models/property'
import City from '#models/city'

export default class extends BaseSeeder {
  async run() {
    // 1. Seed Gujarat Cities
    await City.updateOrCreateMany('name', [
      { name: 'Ahmedabad', propertiesCount: 488, image: '/images/cities/ahmedabad.jpg' },
      { name: 'Surat', propertiesCount: 398, image: '/images/cities/surat.jpg' },
      { name: 'Vadodara', propertiesCount: 468, image: '/images/cities/vadodara.jpg' },
      { name: 'Rajkot', propertiesCount: 336, image: '/images/cities/rajkot.jpg' },
      { name: 'Gandhinagar', propertiesCount: 481, image: '/images/cities/gandhinagar.jpg' },
      { name: 'Bhavnagar', propertiesCount: 218, image: '/images/cities/bhavnagar.jpg' },
      { name: 'Jamnagar', propertiesCount: 185, image: '/images/cities/jamnagar.jpg' },
      { name: 'Junagadh', propertiesCount: 160, image: '/images/cities/junagadh.jpg' },
      { name: 'Anand', propertiesCount: 195, image: '/images/cities/anand.jpg' },
      { name: 'Navsari', propertiesCount: 145, image: '/images/cities/navsari.jpg' },
      { name: 'Bharuch', propertiesCount: 170, image: '/images/cities/bharuch.jpg' },
      { name: 'Vapi', propertiesCount: 210, image: '/images/cities/vapi.jpg' },
    ])

    // 2. Seed Properties (Buy, Rent, Short-term, Trending)
    await Property.updateOrCreateMany('name', [
      // Buy Properties
      {
        name: 'The Juniper Villa',
        city: 'Ahmedabad',
        location: 'Bodakdev, Ahmedabad',
        mode: 'buy',
        type: 'Villa',
        price: 24800000,
        priceLabel: 'INR 2.48 Cr',
        size: 3200,
        bedrooms: 4,
        bathrooms: 4,
        details: '4 BHK · 4 Baths',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=85',
        tag: 'Trending',
        isTrending: true,
        description: 'Spectacular contemporary villa with landscaped garden, private plunge pool, and floor-to-ceiling glass architecture.',
      },
      {
        name: 'Arcadia Sky Residence',
        city: 'Surat',
        location: 'Vesu, Surat',
        mode: 'buy',
        type: 'Apartment',
        price: 17500000,
        priceLabel: 'INR 1.75 Cr',
        size: 2150,
        bedrooms: 3,
        bathrooms: 3,
        details: '3 BHK · 3 Baths',
        image: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1000&q=85',
        tag: 'Popular',
        isTrending: true,
        description: 'Sun-drenched luxury high-rise apartment with expansive city vistas, Italian marble flooring, and designer interiors.',
      },
      {
        name: 'Canyon Palm Estate',
        city: 'Vadodara',
        location: 'Alkapuri, Vadodara',
        mode: 'buy',
        type: 'Bungalow',
        price: 18600000,
        priceLabel: 'INR 1.86 Cr',
        size: 2600,
        bedrooms: 4,
        bathrooms: 3,
        details: '4 BHK · 3 Baths',
        image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1000&q=85',
        tag: 'Featured',
        isTrending: true,
        description: 'Colonial-inspired bungalow surrounded by mature teak and palm trees in prime Alkapuri with generous verandahs.',
      },
      {
        name: 'The Capital Heights',
        city: 'Gandhinagar',
        location: 'Kudasan, Gandhinagar',
        mode: 'buy',
        type: 'Penthouse',
        price: 31000000,
        priceLabel: 'INR 3.10 Cr',
        size: 4100,
        bedrooms: 5,
        bathrooms: 5,
        details: '5 BHK · 5 Baths',
        image: 'https://images.unsplash.com/photo-1600573472556-e636c2acda88?auto=format&fit=crop&w=1000&q=85',
        tag: 'Trending',
        isTrending: true,
        description: 'Triplex penthouse overlooking Gandhinagar greenery with private rooftop deck, jacuzzi, and dedicated elevator.',
      },
      {
        name: 'Sapphire Haven',
        city: 'Rajkot',
        location: 'Kalawad Road, Rajkot',
        mode: 'buy',
        type: 'Apartment',
        price: 8500000,
        priceLabel: 'INR 85 L',
        size: 1550,
        bedrooms: 3,
        bathrooms: 2,
        details: '3 BHK · 2 Baths',
        image: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1000&q=85',
        tag: 'Hot Deal',
        isTrending: true,
        description: 'Vastu-compliant elegant apartment near prime schools, clubhouses, and lifestyle centers on Kalawad Road.',
      },
      {
        name: 'Marble Crest Manor',
        city: 'Bhavnagar',
        location: 'Victoria Park, Bhavnagar',
        mode: 'buy',
        type: 'Bungalow',
        price: 15200000,
        priceLabel: 'INR 1.52 Cr',
        size: 2400,
        bedrooms: 4,
        bathrooms: 3,
        details: '4 BHK · 3 Baths',
        image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1000&q=85',
        tag: 'Featured',
        isTrending: true,
        description: 'Peaceful garden bungalow backing directly onto the natural reserve of Victoria Park with pristine quietude.',
      },
      {
        name: 'Riverside Courtyard',
        city: 'Ahmedabad',
        location: 'Ambli, Ahmedabad',
        mode: 'buy',
        type: 'Villa',
        price: 42000000,
        priceLabel: 'INR 4.20 Cr',
        size: 5200,
        bedrooms: 5,
        bathrooms: 6,
        details: '5 BHK · 6 Baths',
        image: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1000&q=85',
        tag: 'Luxury',
        isTrending: true,
        description: 'Exquisite modern masterpiece with double-height living room, internal courtyard, and heated lap pool.',
      },
      {
        name: 'Green Meadows Residence',
        city: 'Anand',
        location: 'Vidyanagar Road, Anand',
        mode: 'buy',
        type: 'Row House',
        price: 9500000,
        priceLabel: 'INR 95 L',
        size: 1850,
        bedrooms: 3,
        bathrooms: 3,
        details: '3 BHK · 3 Baths',
        image: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=1000&q=85',
        tag: 'Trending',
        isTrending: true,
        description: 'Thoughtfully designed gated community row house with private terrace, manicured lawn, and 24/7 security.',
      },

      // Rent Properties
      {
        name: 'The Larch Loft',
        city: 'Ahmedabad',
        location: 'Prahlad Nagar, Ahmedabad',
        mode: 'rent',
        type: 'Apartment',
        price: 48000,
        priceLabel: 'INR 48,000 / mo',
        size: 1250,
        bedrooms: 2,
        bathrooms: 2,
        details: '2 BHK · 2 Baths',
        image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1000&q=85',
        tag: 'Verified',
        isTrending: false,
        description: 'Furnished modern apartment with central AC, modular kitchen, and private balcony overlooking park.',
      },
      {
        name: 'Casa Mar Coastal',
        city: 'Surat',
        location: 'Dumas Road, Surat',
        mode: 'rent',
        type: 'Home',
        price: 62000,
        priceLabel: 'INR 62,000 / mo',
        size: 1800,
        bedrooms: 3,
        bathrooms: 2,
        details: '3 BHK · 2 Baths',
        image: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1000&q=85',
        tag: 'Popular',
        isTrending: false,
        description: 'Breezy coastal residence with spacious dining area, servant quarters, and covered parking.',
      },
      {
        name: 'Noble Street Studio',
        city: 'Gandhinagar',
        location: 'Infocity, Gandhinagar',
        mode: 'rent',
        type: 'Studio',
        price: 34500,
        priceLabel: 'INR 34,500 / mo',
        size: 850,
        bedrooms: 1,
        bathrooms: 1,
        details: '1 BHK · 1 Bath',
        image: 'https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1000&q=85',
        tag: 'Verified',
        isTrending: false,
        description: 'Tech-friendly minimalist studio with ergonomic workspace, high-speed fiber internet, and gym access.',
      },
      {
        name: 'River Crest Flat',
        city: 'Vadodara',
        location: 'Sayajigunj, Vadodara',
        mode: 'rent',
        type: 'Home',
        price: 55000,
        priceLabel: 'INR 55,000 / mo',
        size: 1600,
        bedrooms: 3,
        bathrooms: 2,
        details: '3 BHK · 2 Baths',
        image: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1000&q=85',
        tag: 'Featured',
        isTrending: false,
        description: 'Central residence close to railway station and Sayaji Garden with power backup and dedicated covered parking.',
      },
      {
        name: 'Skyline Studio Suite',
        city: 'Rajkot',
        location: 'Yagnik Road, Rajkot',
        mode: 'rent',
        type: 'Studio',
        price: 22000,
        priceLabel: 'INR 22,000 / mo',
        size: 650,
        bedrooms: 1,
        bathrooms: 1,
        details: '1 BHK · 1 Bath',
        image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1000&q=85',
        tag: 'Affordable',
        isTrending: false,
        description: 'Cozy and stylish studio unit in the heart of Rajkot commercial hub.',
      },
      {
        name: 'Maple Grove Villa',
        city: 'Bhavnagar',
        location: 'Takhteshwar, Bhavnagar',
        mode: 'rent',
        type: 'Home',
        price: 78000,
        priceLabel: 'INR 78,000 / mo',
        size: 2200,
        bedrooms: 4,
        bathrooms: 3,
        details: '4 BHK · 3 Baths',
        image: 'https://images.unsplash.com/photo-1600573472556-e636c2acda88?auto=format&fit=crop&w=1000&q=85',
        tag: 'Featured',
        isTrending: false,
        description: 'Spacious independent home with private garden and rooftop in a peaceful Bhavnagar neighborhood.',
      },

      // Short-Term Stays
      {
        name: 'Heritage Courtyard Haveli',
        city: 'Ahmedabad',
        location: 'Old City Heritage Quarter, Ahmedabad',
        mode: 'short-term',
        type: 'Villa',
        price: 3500,
        priceLabel: 'INR 3,500 / night',
        size: 1400,
        bedrooms: 2,
        bathrooms: 2,
        details: '2 BHK · 2 Baths',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=85',
        tag: 'Superhost',
        isTrending: false,
        description: 'Restored wooden haveli with carved pillars, open-sky courtyard, and authentic Gujarati hospitality.',
      },
      {
        name: 'The Glass Pavilion Retreat',
        city: 'Gandhinagar',
        location: 'Gift City Road, Gandhinagar',
        mode: 'short-term',
        type: 'Apartment',
        price: 4500,
        priceLabel: 'INR 4,500 / night',
        size: 1100,
        bedrooms: 1,
        bathrooms: 1,
        details: '1 BHK · 1 Bath',
        image: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1000&q=85',
        tag: 'Trending',
        isTrending: false,
        description: 'Ultra-modern glass apartment with skyline views of GIFT City, smart lighting, and pool access.',
      },
      {
        name: 'Sunset Terrace Stay',
        city: 'Ahmedabad',
        location: 'Vastrapur Lake, Ahmedabad',
        mode: 'short-term',
        type: 'City',
        price: 2850,
        priceLabel: 'INR 2,850 / night',
        size: 1100,
        bedrooms: 2,
        bathrooms: 2,
        details: '2 BHK · 2 Baths',
        image: 'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1000&q=85',
        tag: 'Top Rated',
        isTrending: false,
        description: 'Stunning sunset view overlooking the Vastrapur amphitheater and promenade.',
      },
      {
        name: 'The Palm House Coastal',
        city: 'Surat',
        location: 'Dumas Beach Road, Surat',
        mode: 'short-term',
        type: 'Coast',
        price: 3400,
        priceLabel: 'INR 3,400 / night',
        size: 1600,
        bedrooms: 3,
        bathrooms: 2,
        details: '3 BHK · 2 Baths',
        image: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1000&q=85',
        tag: 'Beachfront',
        isTrending: false,
        description: 'Tropical oasis minutes from the beach with palm-lined patio and outdoor barbecue.',
      },
      {
        name: 'Oak View Heritage Flat',
        city: 'Vadodara',
        location: 'Fatehgunj, Vadodara',
        mode: 'short-term',
        type: 'City',
        price: 2200,
        priceLabel: 'INR 2,200 / night',
        size: 780,
        bedrooms: 1,
        bathrooms: 1,
        details: '1 BHK · 1 Bath',
        image: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1000&q=85',
        tag: 'Cozy',
        isTrending: false,
        description: 'Charming vintage flat close to the Laxmi Vilas Palace and university.',
      },
      {
        name: 'Hilltop Retreat',
        city: 'Rajkot',
        location: 'Pradyuman Park, Rajkot',
        mode: 'short-term',
        type: 'Villa',
        price: 4800,
        priceLabel: 'INR 4,800 / night',
        size: 2000,
        bedrooms: 4,
        bathrooms: 3,
        details: '4 BHK · 3 Baths',
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=85',
        tag: 'Exclusive',
        isTrending: false,
        description: 'Sprawling hilltop stay offering panoramic views of Rajkot landscape.',
      },
      {
        name: 'Harbor Loft',
        city: 'Bhavnagar',
        location: 'Ghogha Road, Bhavnagar',
        mode: 'short-term',
        type: 'Coast',
        price: 1900,
        priceLabel: 'INR 1,900 / night',
        size: 620,
        bedrooms: 1,
        bathrooms: 1,
        details: '1 BHK · 1 Bath',
        image: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1000&q=85',
        tag: 'Economy',
        isTrending: false,
        description: 'Modern maritime studio close to Ghogha ferry terminal and coast.',
      },
      {
        name: 'Garden Suite Villa',
        city: 'Gandhinagar',
        location: 'Sector 8, Gandhinagar',
        mode: 'short-term',
        type: 'Villa',
        price: 3100,
        priceLabel: 'INR 3,100 / night',
        size: 1350,
        bedrooms: 2,
        bathrooms: 2,
        details: '2 BHK · 2 Baths',
        image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1000&q=85',
        tag: 'Superhost',
        isTrending: false,
        description: 'Serene garden villa in Gandhinagars lush green sector with private patio.',
      },
    ])
  }
}
