/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CitySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'image', 'name', 'propertiesCount', 'updatedAt'] as const
  $columns = CitySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare image: string | null
  @column()
  declare name: string
  @column()
  declare propertiesCount: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DealerSchema extends BaseModel {
  static $columns = ['agencyName', 'bio', 'city', 'createdAt', 'dealerType', 'email', 'id', 'name', 'officeAddress', 'phone', 'profilePhoto', 'reraNumber', 'updatedAt', 'verificationStatus'] as const
  $columns = DealerSchema.$columns
  @column()
  declare agencyName: string
  @column()
  declare bio: string | null
  @column()
  declare city: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dealerType: string | null
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare officeAddress: string | null
  @column()
  declare phone: string
  @column()
  declare profilePhoto: string
  @column()
  declare reraNumber: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare verificationStatus: string | null
}

export class PropertySchema extends BaseModel {
  static $columns = ['bathrooms', 'bedrooms', 'city', 'createdAt', 'dealerData', 'dealerId', 'description', 'details', 'id', 'image', 'images', 'isTrending', 'location', 'mapUrl', 'mode', 'name', 'price', 'priceLabel', 'size', 'tag', 'type', 'updatedAt'] as const
  $columns = PropertySchema.$columns
  @column()
  declare bathrooms: number
  @column()
  declare bedrooms: number
  @column()
  declare city: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dealerData: string | null
  @column()
  declare dealerId: number | null
  @column()
  declare description: string | null
  @column()
  declare details: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare image: string | null
  @column()
  declare images: string | null
  @column()
  declare isTrending: boolean | null
  @column()
  declare location: string | null
  @column()
  declare mapUrl: string | null
  @column()
  declare mode: string
  @column()
  declare name: string
  @column()
  declare price: bigint | number
  @column()
  declare priceLabel: string
  @column()
  declare size: number | null
  @column()
  declare tag: string | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
